export const platformCapabilities = [
  'Composability',
  'Agent Governance',
  'Multi Framework',
  'Cloud Native',
  'Open Source',
  'Self Hostable',
  'Modular',
  'Cost Optimized',
  'Reliability',
  'Secure',
  'Ease of Use',
]

export const repoPages = [
  {
    slug: 'agent-skills',
    name: 'Agent-Skills',
    repo: 'Agent-Skills',
    centralBenefit: 'Reuse trusted agent capabilities without rebuilding them for every workflow.',
    whatItIs: 'Agent-Skills is a secure skills registry for packaging, versioning, discovering, verifying, and reusing agent capabilities across workflows, runtimes, and teams. Instead of every agent carrying its own custom logic, common capabilities can become reusable skills that are shared, reviewed, governed, and reused across the Agent World.',
    whyImportant: 'As agent systems grow, teams often rebuild the same actions, prompts, tools, and workflow logic again and again. That creates duplication, inconsistent behavior, and weak governance. Agent-Skills turns capabilities into reusable building blocks that are versioned like code, discoverable like packages, organized like infrastructure, and trusted through cryptographic signing.',
    useCases: ['Share approved skills across teams and agent workflows', 'Build new agents faster from reusable capabilities', 'Verify skill provenance before adoption', 'Reduce duplicate implementation across projects', 'Maintain a governed library of agent-ready capabilities', 'Compose workflows from trusted skills instead of one-off scripts'],
    benefits: ['Faster agent development', 'Lower duplication across teams', 'More trusted reuse of capabilities', 'Cleaner governance for agent behavior', 'Easier adoption by engineering teams', 'Better maintainability as the agent ecosystem grows'],
    isPrivate: false,
  },
  {
    slug: 'tool-catalog',
    name: 'Tool-Catalog',
    repo: 'Tool-Catalog',
    centralBenefit: 'Find the right agent-ready tools faster and avoid tool sprawl.',
    whatItIs: 'Tool-Catalog is a structured catalog for discovering, organizing, and managing tools that agents can use across workflows. It gives teams a common place to describe tools, capabilities, categories, usage patterns, and integration points.',
    whyImportant: 'As teams add more tools to agent workflows, discovery becomes messy. Developers may not know which tools already exist, which ones are approved, or which ones are safe to use. Tool-Catalog reduces that friction by making tools discoverable, reusable, and easier to govern.',
    useCases: ['Discover tools by capability or category', 'Maintain metadata for agent-ready tools', 'Help teams avoid duplicate tool integrations', 'Connect tools to skills, agents, and workflows', 'Organize approved tools for enterprise use'],
    benefits: ['Faster tool discovery', 'Less duplication across teams', 'Better governance of tool usage', 'Easier integration planning', 'Cleaner agent workflow design'],
    isPrivate: false,
  },
  {
    slug: 'agent-memory',
    name: 'Agent-Memory',
    repo: 'Agent-Memory',
    centralBenefit: 'Give agents continuity so users do not have to repeat context every time.',
    whatItIs: 'Agent-Memory is a memory layer for context-aware agent systems. It helps agents retain useful context across sessions, workflows, users, and tasks. Public-facing content remains high-level because this repository is private.',
    whyImportant: 'Users should not have to explain the same preferences, project details, decisions, and context every time they interact with an agent. Agent-Memory makes agents more useful by helping them remember relevant context while keeping governance, trust, and security in view.',
    useCases: ['Preserve user preferences across sessions', 'Maintain project and workflow context', 'Support personalized agent experiences', 'Give agents access to prior decisions and outcomes', 'Improve continuity in long-running workflows'],
    benefits: ['Less repeated explanation from users', 'More context-aware agents', 'Better personalization', 'More reliable workflow continuity', 'Stronger foundation for governed memory'],
    isPrivate: true,
  },
  {
    slug: 'prompt-library',
    name: 'Prompt-Library',
    repo: 'Prompt-Library',
    centralBenefit: 'Reuse proven prompts instead of rewriting instructions from scratch.',
    whatItIs: 'Prompt-Library is a repository for reusable prompts, agent instructions, task templates, and workflow patterns. Public-facing content remains high-level because this repository is private.',
    whyImportant: 'Prompts often become scattered across documents, codebases, chats, and experiments. That makes them hard to reuse, improve, govern, or evaluate. Prompt-Library gives teams a structured way to manage prompt assets so agents can behave more consistently across workflows.',
    useCases: ['Store reusable prompts and instructions', 'Standardize agent behavior across teams', 'Maintain task-specific prompt templates', 'Support prompt review and governance', 'Reuse tested instructions in production workflows'],
    benefits: ['Faster workflow setup', 'More consistent agent behavior', 'Less prompt duplication', 'Easier review and improvement', 'Better governance of agent instructions'],
    isPrivate: true,
  },
  {
    slug: 'model-registry',
    name: 'model-registry',
    repo: 'model-registry',
    centralBenefit: 'Choose the right model for each task with better cost, quality, and governance.',
    whatItIs: 'model-registry is a registry for organizing models used across agent systems. It helps teams track model options, capabilities, metadata, providers, constraints, and usage contexts.',
    whyImportant: 'Agent systems often depend on many models. Without a registry, teams can lose track of which model is best for which task, which models are approved, and how cost or quality tradeoffs are managed. model-registry creates a structured model inventory so agents can use models more intelligently and responsibly.',
    useCases: ['Track available models and providers', 'Compare models by capability, cost, and use case', 'Support model routing and selection', 'Maintain approved model metadata', 'Improve governance for model usage'],
    benefits: ['Better model selection', 'Lower model cost waste', 'Clearer model governance', 'More reliable agent workflows', 'Easier multi-model operations'],
    isPrivate: false,
  },
  {
    slug: 'agent-protocols',
    name: 'Agent-Protocols',
    repo: 'Agent-Protocols',
    centralBenefit: 'Make agents work together across tools, frameworks, and systems without custom integrations every time.',
    whatItIs: 'Agent-Protocols defines protocol foundations for interoperable autonomous agents. It supports communication, coordination, identity, discovery, and integration patterns across the Agent World.',
    whyImportant: 'Without shared protocols, every agent integration becomes custom work. That slows adoption and makes agent systems harder to scale. Agent-Protocols helps create a common foundation so agents, tools, services, and frameworks can work together more predictably.',
    useCases: ['Standardize agent-to-agent communication', 'Connect agents across different frameworks', 'Define integration contracts between systems', 'Support identity, discovery, and authorization patterns', 'Build interoperable agent ecosystems'],
    benefits: ['Less custom integration work', 'Better interoperability', 'More portable agent systems', 'Stronger ecosystem consistency', 'Easier multi-framework adoption'],
    isPrivate: false,
  },
  {
    slug: 'agent-registry',
    name: 'Agent-Registry',
    repo: 'Agent-Registry',
    centralBenefit: 'Discover, identify, and manage trusted agents in one place.',
    whatItIs: 'Agent-Registry is a registry layer for organizing agent metadata, identity, capabilities, ownership, lifecycle state, and discovery information.',
    whyImportant: 'As teams create more agents, users need to know which agents exist, what they do, who owns them, whether they are trusted, and where they can be used. Agent-Registry creates a single place to manage agent discovery and visibility.',
    useCases: ['Register agent metadata and capabilities', 'Discover agents by function or domain', 'Track agent ownership and lifecycle', 'Support trusted agent discovery', 'Connect agents to governance workflows'],
    benefits: ['Easier agent discovery', 'Better agent governance', 'Clearer ownership and accountability', 'More reliable reuse of agents', 'Stronger platform visibility'],
    isPrivate: false,
  },
  {
    slug: 'agent-constitution',
    name: 'Agent-Constitution',
    repo: 'Agent-Constitution',
    centralBenefit: 'Give teams clear rules for how agents should behave before they are deployed.',
    whatItIs: 'Agent-Constitution defines principles, rules, constraints, and operating expectations for autonomous agents. It helps teams describe what agents are allowed to do, what they should avoid, and how they should behave in governed environments.',
    whyImportant: 'Agents need boundaries. Without clear rules, behavior can become inconsistent, unsafe, or difficult to review. Agent-Constitution gives teams a governance foundation before agents are deployed into real workflows.',
    useCases: ['Define agent behavior principles', 'Set operating rules for autonomous workflows', 'Support review and approval policies', 'Align agents with organizational expectations', 'Create reusable governance patterns'],
    benefits: ['Clearer behavioral boundaries', 'Better trust in agent systems', 'Stronger governance', 'More consistent agent behavior', 'Safer production adoption'],
    isPrivate: false,
  },
  {
    slug: 'agent-builder',
    name: 'Agent-Builder',
    repo: 'Agent-Builder',
    centralBenefit: 'Assemble agents faster from reusable components and patterns.',
    whatItIs: 'Agent-Builder helps users create agents from reusable building blocks, configuration patterns, tools, skills, prompts, and workflows.',
    whyImportant: 'Building agents from scratch is slow and inconsistent. Teams need repeatable ways to assemble agents without reinventing the same architecture every time. Agent-Builder improves speed and consistency by making agent construction more modular and guided.',
    useCases: ['Build new agents from reusable components', 'Configure agent capabilities', 'Assemble workflows from skills and tools', 'Prototype new agent ideas quickly', 'Standardize agent creation patterns'],
    benefits: ['Faster agent creation', 'Easier experimentation', 'More consistent architecture', 'Lower development effort', 'Better reuse across teams'],
    isPrivate: false,
  },
  {
    slug: 'agent-ops',
    name: 'Agent-Ops',
    repo: 'Agent-Ops',
    centralBenefit: 'Run agents reliably in production with visibility, controls, and operational discipline.',
    whatItIs: 'Agent-Ops is the operations layer for production agent systems. It supports reliability, observability, deployment discipline, controls, and operational workflows.',
    whyImportant: 'Agents are not useful in production unless teams can monitor them, govern them, troubleshoot them, and operate them safely. Agent-Ops brings operational maturity to agent systems so teams can move beyond experiments.',
    useCases: ['Monitor agent behavior in production', 'Track workflow execution and reliability', 'Support deployment and operations practices', 'Manage operational controls and review paths', 'Improve production readiness for agent systems'],
    benefits: ['Better operational visibility', 'More reliable agent workflows', 'Faster incident response', 'Stronger production governance', 'Safer enterprise adoption'],
    isPrivate: false,
  },
  {
    slug: 'agent-idenity',
    name: 'Agent-Idenity',
    repo: 'Agent-Idenity',
    centralBenefit: 'Know which agent is acting, what it can access, and whether it can be trusted.',
    whatItIs: 'Agent-Idenity is an identity layer for trusted agent interactions. It supports identity, access, authentication, and trust concepts for agent systems. Public-facing content remains high-level because this repository is private.',
    whyImportant: 'Autonomous agents need identity. Users and systems should be able to understand which agent is acting, what permissions it has, and whether the action is trusted. Agent-Idenity supports safer agent workflows by strengthening identity and accountability.',
    useCases: ['Identify agents across workflows', 'Support trusted agent interactions', 'Connect identity to access controls', 'Improve auditability of agent actions', 'Support governance and approval flows'],
    benefits: ['Stronger agent accountability', 'Better access control foundations', 'More secure agent interactions', 'Improved governance visibility', 'Higher trust in autonomous systems'],
    isPrivate: true,
  },
  {
    slug: 'agent-security',
    name: 'Agent-Security',
    repo: 'Agent-Security',
    centralBenefit: 'Reduce risk by adding security controls around agent actions, workflows, and access.',
    whatItIs: 'Agent-Security provides security patterns, controls, and safeguards for autonomous agent systems.',
    whyImportant: 'Agents can access tools, data, APIs, and workflows. Without security controls, agent systems can create operational, data, and compliance risk. Agent-Security helps teams protect agent workflows and build safer systems.',
    useCases: ['Define security controls for agent actions', 'Protect sensitive workflows', 'Support secure tool and data access', 'Add review points for risky operations', 'Strengthen enterprise security posture'],
    benefits: ['Lower operational risk', 'Safer agent execution', 'Better access governance', 'Stronger enterprise readiness', 'Improved trust in agent workflows'],
    isPrivate: false,
  },
  {
    slug: 'agent-graph',
    name: 'Agent-Graph',
    repo: 'Agent-Graph',
    centralBenefit: 'Understand relationships between agents, tools, workflows, memory, and decisions.',
    whatItIs: 'Agent-Graph models the relationships inside agent systems. It can represent how agents connect to tools, data, memory, workflows, tasks, and decisions.',
    whyImportant: 'Agent systems become hard to understand as they grow. Users need visibility into how components relate and how decisions flow through the system. Agent-Graph gives teams a structured way to understand and reason about agent ecosystems.',
    useCases: ['Map relationships between agents and tools', 'Understand workflow dependencies', 'Represent decision paths and context', 'Support graph-based reasoning', 'Improve visibility across complex agent systems'],
    benefits: ['Better system understanding', 'Stronger workflow visibility', 'Easier debugging and governance', 'More structured orchestration', 'Clearer dependency management'],
    isPrivate: false,
  },
  {
    slug: 'agent-blueprint',
    name: 'Agent-Blueprint',
    repo: 'Agent-Blueprint',
    centralBenefit: 'Start faster with repeatable patterns for designing agent systems.',
    whatItIs: 'Agent-Blueprint provides reusable architecture patterns, templates, and design references for building agent systems.',
    whyImportant: 'Teams need proven starting points. Without blueprints, every agent project starts from a blank page, causing delays and inconsistent design. Agent-Blueprint helps teams move faster with repeatable patterns.',
    useCases: ['Start new agent projects from templates', 'Reuse proven architecture patterns', 'Standardize agent system design', 'Guide platform implementation', 'Share reference patterns across teams'],
    benefits: ['Faster solution design', 'More repeatable architecture', 'Lower implementation friction', 'Better consistency across projects', 'Easier onboarding for teams'],
    isPrivate: false,
  },
  {
    slug: 'agent-lifecycle-management',
    name: 'agent-lifecycle-management',
    repo: 'agent-lifecycle-management',
    centralBenefit: 'Manage agents from creation to deployment, updates, monitoring, and retirement.',
    whatItIs: 'agent-lifecycle-management supports the lifecycle of agents across design, versioning, deployment, monitoring, maintenance, and retirement.',
    whyImportant: 'Agents evolve. Teams need to know which version is running, where it is deployed, who owns it, and when it should be updated or retired. agent-lifecycle-management creates discipline around agent evolution.',
    useCases: ['Track agent lifecycle stages', 'Manage agent versions and changes', 'Support deployment and retirement workflows', 'Connect lifecycle state to governance', 'Improve production readiness'],
    benefits: ['Better lifecycle visibility', 'More controlled agent evolution', 'Cleaner governance', 'Easier operations management', 'Reduced risk from unmanaged agents'],
    isPrivate: false,
  },
  {
    slug: 'agennext-helper',
    name: 'AGenNext-Helper',
    repo: 'AGenNext-Helper',
    centralBenefit: 'Reduce repetitive platform work with helper utilities and workflow shortcuts.',
    whatItIs: 'AGenNext-Helper provides helper utilities and support functions for AGenNext workflows, automation, and platform operations.',
    whyImportant: 'Small repetitive tasks slow teams down. Helper utilities reduce friction so developers can focus on higher-value platform and agent work.',
    useCases: ['Support internal workflow automation', 'Provide reusable utility functions', 'Reduce repetitive development tasks', 'Improve platform setup and maintenance', 'Assist common engineering workflows'],
    benefits: ['Faster internal workflows', 'Less repetitive work', 'Better developer productivity', 'Easier platform maintenance', 'More consistent support utilities'],
    isPrivate: false,
  },
  {
    slug: 'agent-chat',
    name: 'Agent-Chat',
    repo: 'Agent-Chat',
    centralBenefit: 'Give users a natural chat interface to interact with agents and workflows.',
    whatItIs: 'Agent-Chat supports conversational interfaces for agent systems. It helps users interact with agents through chat-based experiences.',
    whyImportant: 'Users need a simple way to work with agents. Chat is one of the most natural interfaces for asking questions, giving instructions, reviewing outputs, and managing workflows. Agent-Chat makes agent systems easier to access and use.',
    useCases: ['Build chat-based agent interfaces', 'Support human-agent collaboration', 'Trigger workflows from conversation', 'Review and approve agent outputs', 'Create user-facing assistant experiences'],
    benefits: ['Easier user adoption', 'More natural interaction', 'Better workflow accessibility', 'Faster task completion', 'Improved human-agent collaboration'],
    isPrivate: false,
  },
  {
    slug: 'agent-content',
    name: 'Agent-Content',
    repo: 'Agent-Content',
    centralBenefit: 'Create, manage, and publish content faster with agent-assisted workflows.',
    whatItIs: 'Agent-Content supports content workflows for drafting, organizing, reviewing, transforming, and publishing content with agent assistance.',
    whyImportant: 'Content work often involves repeated steps: ideation, drafting, editing, formatting, review, and publishing. Agents can reduce this workload when the process is structured. Agent-Content helps turn content operations into repeatable workflows.',
    useCases: ['Draft content with agent assistance', 'Transform content between formats', 'Organize editorial workflows', 'Support review and publishing steps', 'Reuse content patterns across teams'],
    benefits: ['Faster content production', 'More consistent workflows', 'Less manual formatting and repetition', 'Better content operations', 'Easier scaling of content output'],
    isPrivate: false,
  },
  {
    slug: 'agent-vision',
    name: 'Agent-Vision',
    repo: 'Agent-Vision',
    centralBenefit: 'Let agents understand visual inputs so users can automate image and inspection workflows.',
    whatItIs: 'Agent-Vision supports vision-enabled agent workflows. It connects image understanding, visual inspection, and multimodal reasoning to agent systems.',
    whyImportant: 'Many real-world tasks involve visual information: screenshots, documents, images, diagrams, photos, or inspection data. Agents need visual understanding to support those workflows. Agent-Vision expands what agents can perceive and act on.',
    useCases: ['Analyze images and screenshots', 'Support visual inspection workflows', 'Connect vision models to agents', 'Automate document and image review', 'Build multimodal agent experiences'],
    benefits: ['More capable agents', 'Better support for visual workflows', 'Reduced manual image review', 'Expanded multimodal automation', 'Improved task coverage'],
    isPrivate: false,
  },
  {
    slug: 'agent-assitant',
    name: 'Agent-Assitant',
    repo: 'Agent-Assitant',
    centralBenefit: 'Complete tasks faster through assistant-style agent workflows.',
    whatItIs: 'Agent-Assitant supports assistant-style agent workflows for productivity, task support, and user-facing automation. The repository name appears to contain a typo: Assitant.',
    whyImportant: 'Users need agents that can help with everyday tasks in a simple, accessible way. Assistant-style workflows make agents easier to adopt and more practical for daily use.',
    useCases: ['Build productivity assistants', 'Automate repeated user tasks', 'Support personal or team workflows', 'Coordinate information retrieval and actions', 'Provide user-facing agent experiences'],
    benefits: ['Faster task completion', 'Easier user adoption', 'More practical agent workflows', 'Better productivity support', 'Lower friction for non-technical users'],
    isPrivate: false,
  },
  {
    slug: 'agent-research',
    name: 'Agent-Research',
    repo: 'Agent-Research',
    centralBenefit: 'Explore new agent ideas and turn experiments into reusable platform patterns.',
    whatItIs: 'Agent-Research supports experimentation, research workflows, prototypes, and frontier ideas for autonomous agent systems.',
    whyImportant: 'Agent technology evolves quickly. Teams need a place to test ideas, evaluate patterns, and move promising research into practical platform components. Agent-Research creates a structured space for exploration.',
    useCases: ['Prototype new agent concepts', 'Test experimental workflows', 'Explore emerging agent patterns', 'Validate research ideas', 'Convert experiments into reusable platform components'],
    benefits: ['Faster research iteration', 'Better prototype organization', 'More reusable research outputs', 'Clearer path from experiment to product', 'Stronger innovation pipeline'],
    isPrivate: false,
  },
  {
    slug: 'agent-business',
    name: 'Agent-Business',
    repo: 'Agent-Business',
    centralBenefit: 'Automate business workflows and decision support with agents.',
    whatItIs: 'Agent-Business supports business-focused agent workflows for operations, analysis, coordination, and decision support.',
    whyImportant: 'Business teams often deal with repeated processes, fragmented tools, and manual coordination. Agents can reduce friction when workflows are structured and governed. Agent-Business helps bring agent automation into business operations.',
    useCases: ['Automate business processes', 'Support operational decision-making', 'Coordinate cross-functional tasks', 'Assist business analysis workflows', 'Build domain-specific business agents'],
    benefits: ['Faster business operations', 'Better decision support', 'Less manual coordination', 'More consistent workflows', 'Improved operational efficiency'],
    isPrivate: false,
  },
  {
    slug: 'agent-estate',
    name: 'Agent-Estate',
    repo: 'Agent-Estate',
    centralBenefit: 'Automate real estate workflows for property, documentation, and operations teams.',
    whatItIs: 'Agent-Estate supports real estate and property-related agent workflows, including documentation, property operations, and domain-specific automation.',
    whyImportant: 'Real estate workflows involve repetitive documentation, information retrieval, coordination, and process management. Agents can help reduce manual work and improve consistency. Agent-Estate applies agent workflows to property operations.',
    useCases: ['Support property documentation workflows', 'Automate real estate task handling', 'Assist property operations teams', 'Organize domain-specific agent capabilities', 'Improve real estate process coordination'],
    benefits: ['Faster property workflows', 'Less manual documentation effort', 'Better operational consistency', 'Easier process automation', 'Improved support for real estate teams'],
    isPrivate: false,
  },
  {
    slug: 'agentcservices',
    name: 'AgentcServices',
    repo: 'AgentcServices',
    centralBenefit: 'Coordinate service requests, tasks, and fulfillment workflows with agents.',
    whatItIs: 'AgentcServices supports service-oriented agent workflows for handling requests, coordinating tasks, and supporting service delivery. The repository name appears to contain a typo: AgentcServices.',
    whyImportant: 'Service workflows often require routing, tracking, follow-up, coordination, and response generation. Agents can help automate these flows when the process is clear and governed. AgentcServices brings agent support to service operations.',
    useCases: ['Automate service request workflows', 'Coordinate task fulfillment', 'Support customer or internal service teams', 'Route requests to the right workflow', 'Track service actions and outputs'],
    benefits: ['Faster service handling', 'More consistent operations', 'Better request coordination', 'Reduced manual follow-up', 'Improved service productivity'],
    isPrivate: false,
  },
  {
    slug: 'agent-itsm',
    name: 'Agent-ITSM',
    repo: 'Agent-ITSM',
    centralBenefit: 'Resolve IT incidents and service requests faster with agent-assisted operations.',
    whatItIs: 'Agent-ITSM supports IT service management workflows such as incidents, service requests, triage, knowledge lookup, and operational support.',
    whyImportant: 'IT teams need speed, consistency, and clear escalation paths. Agents can help reduce repetitive work while keeping humans in control of important decisions. Agent-ITSM brings agent workflows to IT operations.',
    useCases: ['Triage incidents', 'Assist service request handling', 'Retrieve knowledge base information', 'Support operational troubleshooting', 'Coordinate IT workflow steps'],
    benefits: ['Faster incident response', 'Better service consistency', 'Reduced support workload', 'Improved IT workflow visibility', 'Stronger operational reliability'],
    isPrivate: false,
  },
  {
    slug: 'agent-data',
    name: 'Agent-Data',
    repo: 'Agent-Data',
    centralBenefit: 'Connect agents to data workflows while keeping governance and reliability in place.',
    whatItIs: 'Agent-Data supports data-focused agent workflows, including access, transformation, management, analysis, and governance patterns.',
    whyImportant: 'Agents often need data to act usefully. But data access must be reliable, secure, and governed. Agent-Data helps teams connect agents to data workflows without losing control over quality and governance.',
    useCases: ['Connect agents to data operations', 'Support data transformation workflows', 'Assist analysis and reporting tasks', 'Apply governance to data access', 'Build data-aware agents'],
    benefits: ['Better data workflow automation', 'More reliable agent outputs', 'Stronger data governance', 'Safer data access patterns', 'Faster analysis workflows'],
    isPrivate: false,
  },
  {
    slug: 'agent-gtm',
    name: 'Agent-GTM',
    repo: 'Agent-GTM',
    centralBenefit: 'Execute sales and marketing workflows faster with agent support.',
    whatItIs: 'Agent-GTM supports go-to-market workflows across sales, marketing, launch planning, campaign support, and customer-facing operations.',
    whyImportant: 'GTM teams handle repeated tasks across messaging, research, outreach, reporting, and campaign execution. Agents can help accelerate those workflows when they are structured and reusable. Agent-GTM applies agent automation to go-to-market execution.',
    useCases: ['Support sales workflows', 'Assist marketing operations', 'Coordinate launch tasks', 'Generate and organize campaign assets', 'Support GTM research and execution'],
    benefits: ['Faster GTM execution', 'Less manual campaign work', 'Better sales and marketing coordination', 'More consistent workflow outputs', 'Improved business productivity'],
    isPrivate: false,
  },
  {
    slug: 'agent-trust',
    name: 'Agent-Trust',
    repo: 'Agent-Trust',
    centralBenefit: 'Help users trust agent systems through accountability, transparency, and reliability patterns.',
    whatItIs: 'Agent-Trust supports trust infrastructure for agent systems, including accountability, transparency, reliability, provenance, and governance patterns.',
    whyImportant: 'Users will not adopt agents they cannot trust. Trust requires visibility into what agents do, why they act, and how their behavior is governed. Agent-Trust helps make agent systems more accountable and trustworthy.',
    useCases: ['Add trust signals to agent workflows', 'Improve agent accountability', 'Support transparency and review', 'Connect trust patterns to governance', 'Strengthen adoption of autonomous systems'],
    benefits: ['Higher user confidence', 'Better governance alignment', 'More accountable agent behavior', 'Stronger enterprise trust posture', 'Safer adoption of agent workflows'],
    isPrivate: false,
  },
  {
    slug: 'agent-world',
    name: 'Agent-World',
    repo: 'Agent-World',
    centralBenefit: 'Understand and navigate the broader agent ecosystem as one connected world.',
    whatItIs: 'Agent-World provides a conceptual and operational layer for understanding how agents, tools, protocols, workflows, governance, and users fit together.',
    whyImportant: 'Agent ecosystems can feel fragmented. Teams need a shared map of how the pieces connect so they can build with confidence. Agent-World helps frame the broader ecosystem as one connected platform.',
    useCases: ['Define Agent World concepts', 'Organize ecosystem-level thinking', 'Explain how platform components connect', 'Support cross-agent coordination patterns', 'Align teams around a shared architecture'],
    benefits: ['Clearer platform narrative', 'Better ecosystem understanding', 'Stronger architectural alignment', 'Easier onboarding for teams', 'More coherent agent strategy'],
    isPrivate: false,
  },
  {
    slug: 'agent-eval',
    name: 'Agent-Eval',
    repo: 'Agent-Eval',
    centralBenefit: 'Measure agent quality before relying on agents in production.',
    whatItIs: 'Agent-Eval supports evaluation workflows for agent quality, reliability, safety, behavior, and performance.',
    whyImportant: 'Teams need evidence before trusting agents in production. Evaluation helps determine whether an agent is accurate, safe, useful, consistent, and cost-effective. Agent-Eval gives teams a way to measure agents before scaling usage.',
    useCases: ['Evaluate agent outputs', 'Test reliability across tasks', 'Measure safety and behavior quality', 'Compare agents or configurations', 'Support production readiness reviews'],
    benefits: ['Better agent reliability', 'Clearer quality measurement', 'Safer production adoption', 'Improved governance decisions', 'More cost-effective scaling'],
    isPrivate: false,
  },
  {
    slug: 'agent-services',
    name: 'Agent-Services',
    repo: 'Agent-Services',
    centralBenefit: 'Reuse shared services instead of rebuilding backend capabilities for every agent.',
    whatItIs: 'Agent-Services provides shared service components and backend building blocks for agent-powered workflows.',
    whyImportant: 'Agent systems often need common backend services: routing, storage, authentication, workflow support, APIs, and operational helpers. Rebuilding these for every agent wastes time and creates inconsistency. Agent-Services gives teams reusable service foundations.',
    useCases: ['Reuse backend services across agents', 'Support shared workflow infrastructure', 'Standardize service integration', 'Reduce repeated service implementation', 'Build modular service-backed agents'],
    benefits: ['Less duplicated backend work', 'Faster platform integration', 'More consistent service patterns', 'Better modularity', 'Stronger foundation for self-hostable deployments'],
    isPrivate: false,
  },
]

export type RepoPage = (typeof repoPages)[number]

export function getRepoPage(slug: string) {
  return repoPages.find((repo) => repo.slug === slug)
}

export function getRepoReadmeUrl(repo: RepoPage) {
  return `https://github.com/AGenNext/${repo.repo}#readme`
}
